runtime: python39
entrypoint: gunicorn -b :$PORT main:app

handlers:
- url: /static
  static_dir: static

env_variables:
  SECRET_KEY: 'your-secret-key-here'
  # DATABASE_URL will be set in GCP console or via gcloud
