# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['desktop_app.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('templates', 'templates'),
        ('static', 'static'),
        ('instance', 'instance'),
    ],
    hiddenimports=[
        'flask',
        'flask_sqlalchemy',
        'flask_login',
        'werkzeug',
        'flask_wtf',
        'flask_socketio',
        'eventlet',
        'psycopg2',
        'gunicorn',
        'jinja2.ext',
        'sqlalchemy.ext.baked',
        'sqlalchemy.ext.declarative',
        'sqlalchemy.orm',
        'werkzeug.security',
        'collections.defaultdict',
        'functools',
        'engineio.async_drivers.threading',
        'engineio.async_drivers.eventlet',
        'socketio.asyncio_namespace',
        'socketio.base_namespace',
        'socketio.client',
        'socketio.server',
        'engineio.server',
        'engineio.client',
        'webview',
        'webview.platforms.winforms',
        'webview.platforms.cocoa',
        'webview.platforms.qt',
        'webview.platforms.gtk',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=2,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='desktop_app',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='favicon.ico',
)
