# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('templates', 'templates'),
        ('static', 'static'),
        ('instance', 'instance'),
    ],
    hiddenimports=[
        'flask',
        'flask_sqlalchemy',
        'flask_login',
        'werkzeug',
        'flask_wtf',
        'flask_socketio',
        'eventlet',
        'psycopg2',
        'gunicorn',
        'jinja2.ext',
        'sqlalchemy.ext.baked',
        'sqlalchemy.ext.declarative',
        'sqlalchemy.orm',
        'werkzeug.security',
        'collections.defaultdict',
        'functools',
        'engineio.async_drivers.threading',
        'engineio.async_drivers.eventlet',
        'socketio.asyncio_namespace',
        'socketio.base_namespace',
        'socketio.client',
        'socketio.server',
        'engineio.server',
        'engineio.client',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)
pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='stitch_daily_menu',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None,
)
